### ISSUE TITLE
xml anchor elements not used (anymore?)

### ISSUE THREAD

**Issue by reschke** [ietf-tools/xml2rfc#1156]
### Describe the issue

It appears that xml2rfc now throws away anchor information from the source document and always uses the "slugifiedName".

Example from rfc9110.xml:

~~~
    <section anchor="range.requests" numbered="true" removeInRFC="false" toc="include" pn="section-14">
      <name slugifiedName="name-range-requests">Range Requests</name>
~~~

So "range.request" should appear in the HTML.

However (rfc9110.html):

~~~
 <h2 id="name-range-requests">
<a href="#section-14" class="section-number selfRef">14. </a><a href="#name-range-requests" class="section-name selfRef">Range Requests</a>
      </h2>
~~~

I believe in the past it used both (one for "id=" one for "href=").

In any case, this is a serious problem as it breaks existing anchors in content.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by reschke** [comment]
Sorry for the noise; apparently the "proper" anchor is on the enclosing element.

It's still bad that the "self link" chooses the wrong anchor, though.

**Comment by royfielding** [comment]
It is not appropriate for the tools to override the anchor names chosen by the authors. We deliberately chose those names and expect them to appear in all section and ToC references. It is still a bug even if the old references work, since we do not want two or three alias nambes fro every section ref. We only want the ones that are authored in the XML.
