### ISSUE TITLE
Remove link to rfc-local.css

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-tools/xml2rfc#470]
`owner:henrik@levkowetz.com` `type_defect`   |    by martin.thomson@gmail.com

___

This file doesn't exist and so you have browsers making requests that inevitably 404.

The right way to manage style changes is through the --css argument.

___
_Issue migrated from trac:470 at 2022-02-08 07:04:36 +0000_

**Comment by kesara** [comment]
@martinthomson, I'm not sure any work is happening on RFC7992bis (https://github.com/rfc-format/draft-iab-html-rfc-bis)
But this seems like an issue that needs to be addressed elsewhere?

**Comment by martinthomson** [comment]
This is the place that the change is made, but if your point is that you won't make a change until RFC 7992 is revised, that's defensible (even if I would argue it isn't very nice).

A compromise here would be to make the inclusion of the link optional.  I'd even go so far as to suggest that the *addition* of the link be optional for those who care about strict adherence to an RFC, but then if the RPC feel like they need to include links to rfc-local.css AND they find managing options cumbersome, maybe that is too much to ask.

Now that this is here, I'm willing to provide a pull request to make an option happen if that is acceptable.

**Comment by adamroach** [comment]
@martinthomson:
> In addition to my earlier comments, most user agents provide options for style sheet overrides that render this mechanism moot

This was true back in the 1990s and early 2000s. Excluding Firefox, can you post a screenshot of the menu item or other affordance that allows you to do this today?


> This is the place that the change is made, but if your point is that you won't make a change until RFC 7992 is revised, that's defensible (even if I would argue it isn't very nice).

I think the sticking point here is that there was active discussion about the issue of bike-shedding the style, and allowing a local file that overrides whatever is baked in was the solution that emerged from that conversation. If we, as the site operator of sites that serve up RFCs, are concerned about spurious 404s, then the solution is to do the same thing website owners have been doing since 1999 regarding `favicon.ico`: put a file there. If you want to be fancy about it, make it blank and include a `Cache-Control: immutable` header field so clients only request it once, ever.

And _because_ it was an active topic of discussion, I think anything short of waiting for community approval to remove this requirement would be inappropriate.

> A compromise here would be to make the inclusion of the link optional. I'd even go so far as to suggest that the _addition_ of the link be optional for those who care about strict adherence to an RFC, but then if the RPC feel like they need to include links to rfc-local.css AND they find managing options cumbersome, maybe that is too much to ask.

That's not much of a compromise for anyone who wants to actually take advantage of local styling. You're forcing them to update their setup from a trivial file retrieval to a system to run `xml2rfc` locally, which is significantly more complex.

**Comment by jrlevine** [comment]
I agree that if this is a problem, by far the easiest solution is to put stub versions of rfc-local.css on our web servers.

**Comment by martinthomson** [comment]
@adamroach, I wasn't referring so much to the Firefox `View>PageStyle>*` item, but more to tools like Stylus ([Firefox](https://addons.mozilla.org/en-US/firefox/addon/styl-us/), [Chrome](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne)) or [Stylish](https://userstyles.org/).

These exist and are far more effective than any poorly thought-out mechanism that - for most users - involves placing content in a location they don't control.  How many people make copies of RFCs?  How many of those want local styling and aren't in a position to regenerate the HTML (with `xml2rfc --css` or whatever option we contemplate)?  On the other side of this, how many people make an additional useless fetch?

Probably more pertinent a question: how many people actually use this facility?

**Comment by martinthomson** [comment]
Another piece of relevant information I forgot to include: a links to a stylesheet in the header of an HTML file [blocks rendering](https://stackoverflow.com/questions/60774978/how-does-css-blocks-rendering).  This means that loading the page is slower than it needs to be.  Now, rfc-editor.org is hardly winning speed prizes, but the round trip needed to respond with 404 isn't doing that any favours.

**Comment by adamroach** [comment]
> Another piece of relevant information I forgot to include: a links to a stylesheet in the header of an HTML file [blocks rendering](https://stackoverflow.com/questions/60774978/how-does-css-blocks-rendering). This means that loading the page is slower than it needs to be. Now, rfc-editor.org is hardly winning speed prizes, but the round trip needed to respond with 404 isn't doing that any favours.

...but no slower than a 200 response would cause. If you want to help the RFC Editor IT staff configure H2 push to proactively serve an empty CSS file, I'm definitely voting to you to do that work -- otherwise, this is starting to look like concern trolling (and unactionable concern trolling at that, as this group would be overstepping its authority if it were to make changes without community consultation).

**Comment by martinthomson** [comment]
@adamroach, I'm proposing to remove the link on the grounds that it is a) useless, and b) wasteful.  That is all.

I think that what you are implying is that because this functionality is specified in an RFC, this group cannot make a change - even to make the feature optional - without changing that RFC.  The condition there is what I'm struggling with.  I agree that we don't have the authority *here* to overrule an RFC that xml2rfc is bound to comply with (not that that has been a concern in the past), but that's not what I'm asking for.  I'm even offering to do the work.

**Comment by adamroach** [comment]
> I think Adam is arguing that from his perspective neither a) or b) above is true. The commentary on process is relevant, but not the critical part of the argument.
> 
> Adam, could you confirm?

That's true, but I don't think it's the sticking point. The sticking point is that the consensus position of the folks who had this conversation last time around didn't think a) was true, and that consensus is what ended up codified in the RFC. In other words, I'm not arguing this _from my perspective_; I'm arguing it from the perspective of the wider conversation we had with a larger group of people.

I'm entirely unsure what @martinthomson believes he is offering to do when he says "offering to do the work." Is this an offer to gather consensus in the impending RSWG? If so, great. Go for it. I'll lay out my position in that forum, and we can have a community discussion about it. Maybe, with experience under our belt, the outcome will align with what Martin wants to happen. But if it's an offer to use _this_ rather obscure forum to make what is basically a unilateral change to contravene what the RFC says, then I think we're at irreconcilable cross purposes.

**Comment by adamroach** [comment]
To be clear, it's not the process _per se_: it's the principle of consulting the community before making community-impacting changes. I'm not hung up on getting a new RFC out the door; I'm hung up on making sure that stakeholders have an opportunity to participate in the conversation.

**Comment by martinthomson** [comment]
> I'm entirely unsure what @martinthomson believes he is offering to do when he says "offering to do the work."

I was simply offering to add a --rfc-local flag to xml2rfc (or the converse) so that the redundant link could be dropped, while maintaining RFC 7992 compliance for the sticklers.  I certainly do plan to add this to the list of issues for RFC799x revisions, but I think that would come after a discussion about the future of the suite as a whole.
