### ISSUE TITLE
Index HTML doesn't show primary index entries in bold

### ISSUE THREAD

**Issue by cabo** [ietf-tools/xml2rfc#756]
Traditionally, primary entries in an index are shown in bold.

The current code for xml2rfc appears to entirely ignore the primary= attribute on irefs.

This needs to be fixed together with #688, #689, #690, but maybe could receive some attention first.

**Comment by MikeBishop** [comment]
This definitely impacts the usability of indexes.  In https://github.com/cabo/kramdown-rfc/issues/167, kramdown-rfc added an option to collapse the references within the section that defines a term and simply list that section in the index.  However, the section is buried among all the other entries.

In the HTML rendering, that's not so bad, since the instances of the indexed term are also links to the section that defines the term.  But looking at the text output, it's unclear which entry in the index is the definition.

I'd like to see the instance marked primary given as the first entry and possibly bolded.
