### ISSUE TITLE
v2v3 converter outputs syntax that would work with sane grammar

### ISSUE THREAD

**Issue by cabo** [ietf-tools/xml2rfc#850]
Please see https://github.com/cabo/kramdown-rfc/issues/175 for details.

This can be fixed by fixing the grammar to allow <contact in <li and/or by recreating the redundant <t tags deleted by the converter.
Obviously, I'd prefer a grammar fix, but that seems to be politically charged, so maybe working around the grammar bug is easier overall.

Note that this is an actual, everyday problem as it is not uncommon to place contacts into a list.

**Comment by JayDaley** [comment]
Since we're only talking about the v2v3 convertor then changing that not strip the \<t\> tags when there is a \<contact\> inside an \<li\> seems the best way forward as that works and it doesn't require a grammar change.

**Comment by cabo** [comment]
Yes.
Bump?

**Comment by ajeanmahoney** [comment]
In order to create nested lists, ``<t>`` has to be used around text that precedes a nested list (that is, text in ``<li>`` or ``<dd>``). maybe ``xml2rfc --v2v3`` shouldn't strip any ``<t>``s from ``<li>``? Sometimes RFC editors create nested lists to improve readability. Keeping any ``<t>``s in place would be helpful. 

Example nested list:
```
<ul>
  <li>An unordered list item (this text doesn't need to be wrapped in the t element).</li>
  <li>
    <t>Some text that precedes the nested list (this has to be wrapped in the t element):</t>
    <ul>
      <li>Nested list item foo</li>
      <li>Nested list item bar</li>
    </ul>
  </li>
</ul>
```

**Comment by kesara** [comment]
I have [draft PR](https://github.com/ietf-tools/xml2rfc/pull/972) that preserves `<t>` inside `<li>` and `<ol>` but this change creates a lot of unintentional changes.
Have a look at tests output updates in https://github.com/ietf-tools/xml2rfc/pull/972/commits/952a3fa9d601c499f35edfebaf6f9765fe57ef66

**Comment by cabo** [comment]
Essentially, we are building a workaround for a grammar bug, because we don't dare to fix the grammar bug.
The most surgical approach would be to test whether the simple result (existing logic) would violate the grammar and only apply the fix when that happens.

**Comment by rjsparks** [comment]
I could be wrong, but I have the impression that if someone with the skill/drive to do so did the work to regularize what can be contained in what, that the path through approval would not meet a lot of resistance. It would be really nice if we could just _do_ that, and change the code once rather than piecemeal.

**Comment by jrlevine** [comment]
We had a plan to do that the last couple of months I was tRSE but it didn't happen. I agree that we wouldn't see much resistance, give or take whether it breaks existing XML and/or we have a plan to update the old stuff.
