### ISSUE TITLE
Unicode characters in SVG are being garbled

### ISSUE THREAD

**Issue by martinthomson** [ietf-tools/xml2rfc#924]
### Describe the issue

Unicode characters in `<text>` elements of SVG are being garbled by something in the process of rendering or sanitizing that xml2rfc performs on SVG.

These appear to first be turned into character references, like `&#1234;`, which are subsequently quoted, producing `&amp;#1234;`, which puts the literal character reference on the screen rather than the intended character.

It should not be necessary to convert Unicode into character references like this.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by martinthomson** [comment]
Fixed by #832 apparently, just not in a released version just yet.

**Comment by kesara** [comment]
#832 was released in [v3.13.1.](https://github.com/ietf-tools/xml2rfc/releases/tag/v3.13.1).

The draft in question [draft-ietf-quic-load-balancers-15](https://www.ietf.org/archive/id/draft-ietf-quic-load-balancers-15.xml), already has Unicode characters represented in `&amp;#1234;` format.
When Unicode characters are represented correctly like `&#1234;` (or as the character itself), `xml2rfc` generates expected results.

I did some tests with original source: [draft-ietf-quic-load-balancers.md](https://github.com/quicwg/load-balancers/blob/main/draft-ietf-quic-load-balancers.md).
This doesn't seem to be an issue with `xml2rfc` or `kramdown-rfc` since both tools are rending the file correctly.

If authors haven't modified `draft-ietf-quic-load-balancers-15.xml`, this could be a bug in the datatracker submission process.

**Comment by martinthomson** [comment]
That's good information.  Should I open an issue on the datatracker for this then?

**Comment by kesara** [comment]
I've created https://github.com/ietf-tools/datatracker/issues/4643
I haven't been able to reproduce this on datatracker yet.
